# Generated by Django 4.2.1 on 2023-10-24 14:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Слаг')),
                ('description', models.TextField(max_length=1500, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('edited_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('status', models.CharField(choices=[(0, 'В драфте'), (1, 'Опубликовано'), (2, 'Удалено')], default=0, verbose_name='Статус')),
                ('author', models.ForeignKey(on_delete=models.SET('Deleted'), related_name='quizzes', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
    ]
